// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jehvkpgawgdulfstndrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplaHZrcGdhd2dkdWxmc3RuZHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MzYzMjIsImV4cCI6MjA1ODIxMjMyMn0.altSgc_KSuTiDoTvJO3HW7_sg1fBR_gTOUcnWaq9L0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);